# Generated by Django 3.0.3 on 2020-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('auto_fb_post_mode', models.BooleanField()),
                ('category_id', models.IntegerField()),
                ('currencycode', models.TextField()),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donators', models.IntegerField()),
                ('days_active', models.IntegerField()),
                ('days_created', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('has_beneficiary', models.BooleanField()),
                ('visible_in_search', models.BooleanField()),
                ('status', models.IntegerField()),
                ('deactivated', models.BooleanField()),
                ('state', models.TextField()),
                ('is_launched', models.BooleanField()),
                ('campaign_hearts', models.IntegerField()),
                ('social_share_total', models.IntegerField()),
                ('is_charity', models.BooleanField()),
            ],
        ),
    ]
