# Generated by Django 3.0.5 on 2020-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='auto_fb_post_mode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deactivated',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='has_beneficiary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_charity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_launched',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='visible_in_search',
            field=models.TextField(),
        ),
    ]
