# Generated by Django 3.0.5 on 2020-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200407_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
