# Generated by Django 3.0.5 on 2020-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200407_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='days_created',
            field=models.IntegerField(null=True),
        ),
    ]
