# Generated by Django 3.0.3 on 2020-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_campaign_campaign_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
